travis:
  secure:
    BINSTAR_TOKEN: IoKlmlsyD17IJlaPGi1kJn88ly7dgQziSIUYCr5UmncxRu6sDPxotM8AwESIN6audQkzwhUybjLdCp5XN1gHPyV1p/1/KA+JT3R4jwJoUdF0vAN01VACbUv+d6+uCjjY5s0dmqKi7D/Zci7NtONX3PTt4zLzJlG3zF1FM7cuctM0NhYAhdXUksymv6hcYSAMAA0h6J8dMLSz59GtBqjgQhbe4fdapJugiFNxI0lhx17ez6WkB1uFAA6wLbkINfYmRNePHI4eBGXpa8rCXQ77EDSYCw60IrdWJfBsS8TrEOjw3KIIO7qLi/VKAhNvoH5WLNUtgtjsW9gTHVSek+qPmI5/DUZELBB9ikgZ4uGbR+0lobP+L4G7jwMBCwlrWp4eC1D00TORNOPOYNaEk2LiPBiG77ck9mbxbhUC2kGL9CxzJ6dD6NNn1QMUCmKEGSonOWVkXjNz4yTPZRC4PwqhtwCyNYMYnYxoQy055t2ffwbHia0azPL2xJOEYxRMlJYWHaRlohU/AlfzqNQ4yGMEwGMo7MV2ZvCTM9Vv3WgRZGDcvBNdEIsNMfl+9uzRCrwlMMPe8H3wklciUZC6qoW62QF8hEfUxK1oIxyv3eh2aUKf1fWksljG2JeFkJWjxVP/MxF5BQKP9GLBHj9Xim9RrID+g+Y9M/T82WWh7LFdseI=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
